sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
